//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sistemaRestaurante.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Almacen
    {
        public int idAlmacen { get; set; }
        public Nullable<int> idProductoC { get; set; }
        public Nullable<double> cantidadDisponible { get; set; }
        public string unidad { get; set; }
    
        public virtual ProductosCompra ProductosCompra { get; set; }
    }
}
