//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sistemaRestaurante.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Almacen
    {
        public int idAlmacen { get; set; }
        public Nullable<int> idProductoC { get; set; }
        public Nullable<double> cantidadDisponible { get; set; }
        public string unidad { get; set; }
    
        public virtual ProductosCompra ProductosCompra { get; set; }
    }
}
