//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sistemaRestaurante.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComprasdeProductos
    {
        public int idCompradeProductos { get; set; }
        public string Nombre { get; set; }
        public Nullable<decimal> PrecioUnidad { get; set; }
        public Nullable<int> CantidadCompra { get; set; }
        public Nullable<System.DateTime> FechadeCompra { get; set; }
        public Nullable<decimal> TotalaPagar { get; set; }
        public Nullable<int> idProveedor { get; set; }
        public Nullable<int> idUsuario { get; set; }
        public Nullable<int> idAlmacen { get; set; }
    
        public virtual Almacen Almacen { get; set; }
        public virtual Proveedores Proveedores { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        public virtual Usuarios Usuarios1 { get; set; }
    }
}
