//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sistemaRestaurante.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallesCompra
    {
        public int idDetallesC { get; set; }
        public Nullable<int> idProductoC { get; set; }
        public Nullable<double> precioCompra { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<decimal> totalProducto { get; set; }
        public Nullable<int> idCompra { get; set; }
    
        public virtual Compraas Compraas { get; set; }
        public virtual ProductosCompra ProductosCompra { get; set; }
    }
}
