//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sistemaRestaurante.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallesVenta
    {
        public int idDetallesV { get; set; }
        public Nullable<int> idProductoV { get; set; }
        public Nullable<double> precioCompra { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<decimal> totalProducto { get; set; }
        public Nullable<int> idVenta { get; set; }
    
        public virtual ProductosVenta ProductosVenta { get; set; }
        public virtual Ventas Ventas { get; set; }
    }
}
