//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sistemaRestaurante.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallesVenta
    {
        public int idDetallesV { get; set; }
        public Nullable<int> idProductoV { get; set; }
        public Nullable<double> precioCompra { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<decimal> totalProducto { get; set; }
        public Nullable<int> idVenta { get; set; }
    
        public virtual ProductosVenta ProductosVenta { get; set; }
        public virtual Ventas Ventas { get; set; }
    }
}
