//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sistemaRestaurante.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class IngredientesparaProductos
    {
        public int idIngrediente { get; set; }
        public Nullable<int> idProducto { get; set; }
        public Nullable<int> idAlmacen { get; set; }
        public Nullable<int> CantidadNecesaria { get; set; }
        public string tipodeunidad { get; set; }
    
        public virtual Almacen Almacen { get; set; }
        public virtual Productos Productos { get; set; }
    }
}
