//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sistemaRestaurante.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class IngredientesparaProductos
    {
        public int idIngrediente { get; set; }
        public Nullable<int> idProducto { get; set; }
        public Nullable<int> idAlmacen { get; set; }
        public Nullable<int> CantidadNecesaria { get; set; }
        public string tipodeunidad { get; set; }
    
        public virtual Almacen Almacen { get; set; }
        public virtual Productos Productos { get; set; }
    }
}
