//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sistemaRestaurante.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductosOrden
    {
        public int idProductoOrden { get; set; }
        public Nullable<int> idProducto { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<decimal> TotalProducto { get; set; }
        public Nullable<int> idOrden { get; set; }
    
        public virtual Ordenes Ordenes { get; set; }
        public virtual Productos Productos { get; set; }
    }
}
