//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sistemaRestaurante.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductosOrden
    {
        public int idProductoOrden { get; set; }
        public Nullable<int> idProducto { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<decimal> TotalProducto { get; set; }
        public Nullable<int> idOrden { get; set; }
    
        public virtual Ordenes Ordenes { get; set; }
        public virtual Productos Productos { get; set; }
    }
}
