//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sistemaRestaurante.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recetas
    {
        public int idReceta { get; set; }
        public Nullable<int> idProductoV { get; set; }
        public Nullable<int> idProductoC { get; set; }
        public Nullable<int> cantidadProdIngrediente { get; set; }
    
        public virtual ProductosCompra ProductosCompra { get; set; }
        public virtual ProductosVenta ProductosVenta { get; set; }
    }
}
